import aishwaryaImg from "../../../assets/MentorPage/image-one.jpg";
import rajivImg from "../../../assets/MentorPage/image-two.jpg";
import abhinavImg from "../../../assets/MentorPage/image-three.jpg";
import snehaImg from "../../../assets/MentorPage/image-four.jpg";

const studentsData = [
  {
    id: "student-aishwarya",
    name: "Aishwarya R",
    role: "B.Des Student, IIT Bombay",
    image: aishwaryaImg,
    skills: ["Figma", "UX Research", "Prototyping"],
    projects: 5,
    interests: "Design Thinking, Mobile UX",
  },
  {
    id: "student-rajiv",
    name: "Rajiv Mehta",
    role: "B.Tech CSE, NIT Trichy",
    image: rajivImg,
    skills: ["React", "Node.js", "MongoDB"],
    projects: 8,
    interests: "Full Stack Development, Open Source",
  },
  {
    id: "student-abhinav",
    name: "Abhinav Suri",
    role: "MCA, VIT University",
    image: abhinavImg,
    skills: ["JavaScript", "UI Libraries", "Project Planning"],
    projects: 6,
    interests: "Frontend Architectures",
  },
  {
    id: "student-sneha",
    name: "Sneha Varun",
    role: "BSc Data Science, Amrita University",
    image: snehaImg,
    skills: ["Python", "ML", "Pandas"],
    projects: 7,
    interests: "Machine Learning, NLP",
  },
  {
    id: "student-aishwarya",
    name: "Aishwarya R",
    role: "B.Des Student, IIT Bombay",
    image: aishwaryaImg,
    skills: ["Figma", "UX Research", "Prototyping"],
    projects: 5,
    interests: "Design Thinking, Mobile UX",
  },
  {
    id: "student-rajiv",
    name: "Rajiv Mehta",
    role: "B.Tech CSE, NIT Trichy",
    image: rajivImg,
    skills: ["React", "Node.js", "MongoDB"],
    projects: 8,
    interests: "Full Stack Development, Open Source",
  },
  {
    id: "student-abhinav",
    name: "Abhinav Suri",
    role: "MCA, VIT University",
    image: abhinavImg,
    skills: ["JavaScript", "UI Libraries", "Project Planning"],
    projects: 6,
    interests: "Frontend Architectures",
  },
  {
    id: "student-sneha",
    name: "Sneha Varun",
    role: "BSc Data Science, Amrita University",
    image: snehaImg,
    skills: ["Python", "ML", "Pandas"],
    projects: 7,
    interests: "Machine Learning, NLP",
  },
  {
    id: "student-aishwarya",
    name: "Aishwarya R",
    role: "B.Des Student, IIT Bombay",
    image: aishwaryaImg,
    skills: ["Figma", "UX Research", "Prototyping"],
    projects: 5,
    interests: "Design Thinking, Mobile UX",
  },
  {
    id: "student-rajiv",
    name: "Rajiv Mehta",
    role: "B.Tech CSE, NIT Trichy",
    image: rajivImg,
    skills: ["React", "Node.js", "MongoDB"],
    projects: 8,
    interests: "Full Stack Development, Open Source",
  },
  {
    id: "student-abhinav",
    name: "Abhinav Suri",
    role: "MCA, VIT University",
    image: abhinavImg,
    skills: ["JavaScript", "UI Libraries", "Project Planning"],
    projects: 6,
    interests: "Frontend Architectures",
  },
  {
    id: "student-sneha",
    name: "Sneha Varun",
    role: "BSc Data Science, Amrita University",
    image: snehaImg,
    skills: ["Python", "ML", "Pandas"],
    projects: 7,
    interests: "Machine Learning, NLP",
  },
  {
    id: "student-aishwarya",
    name: "Aishwarya R",
    role: "B.Des Student, IIT Bombay",
    image: aishwaryaImg,
    skills: ["Figma", "UX Research", "Prototyping"],
    projects: 5,
    interests: "Design Thinking, Mobile UX",
  },
  {
    id: "student-rajiv",
    name: "Rajiv Mehta",
    role: "B.Tech CSE, NIT Trichy",
    image: rajivImg,
    skills: ["React", "Node.js", "MongoDB"],
    projects: 8,
    interests: "Full Stack Development, Open Source",
  },
  {
    id: "student-abhinav",
    name: "Abhinav Suri",
    role: "MCA, VIT University",
    image: abhinavImg,
    skills: ["JavaScript", "UI Libraries", "Project Planning"],
    projects: 6,
    interests: "Frontend Architectures",
  },
  {
    id: "student-sneha",
    name: "Sneha Varun",
    role: "BSc Data Science, Amrita University",
    image: snehaImg,
    skills: ["Python", "ML", "Pandas"],
    projects: 7,
    interests: "Machine Learning, NLP",
  },
  {
    id: "student-aishwarya",
    name: "Aishwarya R",
    role: "B.Des Student, IIT Bombay",
    image: aishwaryaImg,
    skills: ["Figma", "UX Research", "Prototyping"],
    projects: 5,
    interests: "Design Thinking, Mobile UX",
  },
  {
    id: "student-rajiv",
    name: "Rajiv Mehta",
    role: "B.Tech CSE, NIT Trichy",
    image: rajivImg,
    skills: ["React", "Node.js", "MongoDB"],
    projects: 8,
    interests: "Full Stack Development, Open Source",
  },
  {
    id: "student-abhinav",
    name: "Abhinav Suri",
    role: "MCA, VIT University",
    image: abhinavImg,
    skills: ["JavaScript", "UI Libraries", "Project Planning"],
    projects: 6,
    interests: "Frontend Architectures",
  },
  {
    id: "student-sneha",
    name: "Sneha Varun",
    role: "BSc Data Science, Amrita University",
    image: snehaImg,
    skills: ["Python", "ML", "Pandas"],
    projects: 7,
    interests: "Machine Learning, NLP",
  },

  {
    id: "student-abhinav",
    name: "Abhinav Suri",
    role: "MCA, VIT University",
    image: abhinavImg,
    skills: ["JavaScript", "UI Libraries", "Project Planning"],
    projects: 6,
    interests: "Frontend Architectures",
  },
  {
    id: "student-sneha",
    name: "Sneha Varun",
    role: "BSc Data Science, Amrita University",
    image: snehaImg,
    skills: ["Python", "ML", "Pandas"],
    projects: 7,
    interests: "Machine Learning, NLP",
  },
  {
    id: "student-aishwarya",
    name: "Aishwarya R",
    role: "B.Des Student, IIT Bombay",
    image: aishwaryaImg,
    skills: ["Figma", "UX Research", "Prototyping"],
    projects: 5,
    interests: "Design Thinking, Mobile UX",
  },
  {
    id: "student-rajiv",
    name: "Rajiv Mehta",
    role: "B.Tech CSE, NIT Trichy",
    image: rajivImg,
    skills: ["React", "Node.js", "MongoDB"],
    projects: 8,
    interests: "Full Stack Development, Open Source",
  },
];

export default studentsData;
