// src/data/requestedReviewData.js
import projectImg from "../../../../assets/For Mentor/ReviewLandingPage/ai-tutor.png";

export const projectsData = [
  {
    id: 1,
    title: "AI-Powered Tutoring System",
    description: "An AI-powered tutoring system uses artificial intelligence to create personalized learning experiences for students. This system acts as a virtual tutor, offering support 24/7, and provides valuable insights into a student's progress for both teachers and parents.",
    date: "Aug 20, 2025",
    authors: "Rajesh, John, Priya",
    skills: ["React.js", "Next.js", "JavaScript (ES6+)", "Responsive Design"],
    image: projectImg,
  },
  {
    id: 2,
    title: "AI-Powered Tutoring System",
    description: "An AI-powered tutoring system uses artificial intelligence to create personalized learning experiences for students. This system acts as a virtual tutor, offering support 24/7, and provides valuable insights into a student's progress for both teachers and parents.",
    date: "Aug 20, 2025",
    authors: "Rajesh, John, Priya",
    skills: ["React.js", "Next.js", "JavaScript (ES6+)", "Responsive Design"],
    image: projectImg,
  },
  {
    id: 3,
    title: "AI-Powered Tutoring System",
    description: "An AI-powered tutoring system uses artificial intelligence to create personalized learning experiences for students. This system acts as a virtual tutor, offering support 24/7, and provides valuable insights into a student's progress for both teachers and parents.",
    date: "Aug 20, 2025",
    authors: "Rajesh, John, Priya",
    skills: ["React.js", "Next.js", "JavaScript (ES6+)", "Responsive Design"],
    image: projectImg,
  },
  {
    id: 4,
    title: "AI-Powered Tutoring System",
    description: "An AI-powered tutoring system uses artificial intelligence to create personalized learning experiences for students. This system acts as a virtual tutor, offering support 24/7, and provides valuable insights into a student's progress for both teachers and parents.",
    date: "Aug 20, 2025",
    authors: "Rajesh, John, Priya",
    skills: ["React.js", "Next.js", "JavaScript (ES6+)", "Responsive Design"],
    image: projectImg,
  },
  {
    id: 5,
    title: "AI-Powered Tutoring System",
    description: "An AI-powered tutoring system uses artificial intelligence to create personalized learning experiences for students. This system acts as a virtual tutor, offering support 24/7, and provides valuable insights into a student's progress for both teachers and parents.",
    date: "Aug 20, 2025",
    authors: "Rajesh, John, Priya",
    skills: ["React.js", "Next.js", "JavaScript (ES6+)", "Responsive Design"],
    image: projectImg,
  },
  {
    id: 6,
    title: "Personal Finance Tracker",
    description: "A web application to track personal finances, manage budgets, and visualize spending habits.",
    date: "Sep 1, 2025",
    authors: "Anjali, David",
    skills: ["Node.js", "Express", "MongoDB", "React.js"],
    image: projectImg,
  },
  {
    id: 7,
    title: "E-commerce Platform",
    description: "A full-stack e-commerce site with user authentication, product listings, and a shopping cart.",
    date: "Sep 5, 2025",
    authors: "Michael, Sarah",
    skills: ["Django", "Python", "HTML", "CSS"],
    image: projectImg,
  },
  {
    id: 8,
    title: "Social Media Dashboard",
    description: "A dashboard to monitor social media metrics and engagement across various platforms.",
    date: "Sep 10, 2025",
    authors: "Chris, Emily",
    skills: ["Vue.js", "Firebase", "API Integration"],
    image: projectImg,
  },
  {
    id: 9,
    title: "Weather App",
    description: "A real-time weather application that fetches data from a weather API and displays it in a user-friendly interface.",
    date: "Sep 15, 2025",
    authors: "Alex, Jessica",
    skills: ["HTML", "CSS", "JavaScript", "REST APIs"],
    image: projectImg,
  },
  {
    id: 10,
    title: "Task Management Tool",
    description: "A tool to help teams manage tasks, set deadlines, and track project progress.",
    date: "Sep 20, 2025",
    authors: "Ryan, Olivia",
    skills: ["React", "Redux", "Node.js", "PostgreSQL"],
    image: projectImg,
  },
];
