import avatar from "../../../../assets/EmployeerDashboard/EmployerApplication/avatar.jpg";

const InterviewedData = {
  totalInterviewed: 125,
  ribbonLabel: "Interviewed",
  candidates: [
    {
      id: 1,
      name: "Priya Sharma",
      company: "TechNova Solutions",
      role: "Data Analyst",
      location: "Bengaluru",
      experience: "3 years",
      status: "Actively looking for job",
      matchPercent: 88,
      avatar,
      skills: ["Python", "Tableau", "SQL", "Responsive Design"],
    },
    {
      id: 2,
      name: "Amit Verma",
      company: "InnoTech Pvt Ltd",
      role: "Frontend Developer",
      location: "Hyderabad",
      experience: "2 years",
      status: "Actively looking for job",
      matchPercent: 88,
      avatar,
      skills: ["React", "JavaScript", "CSS", "Redux"],
    },
    {
      id: 3,
      name: "Amit Verma",
      company: "InnoTech Pvt Ltd",
      role: "Frontend Developer",
      location: "Hyderabad",
      experience: "2 years",
      status: "Actively looking for job",
      matchPercent: 95,
      avatar,
      skills: ["React", "JavaScript", "CSS", "Redux"],
    },
     {
      id: 4,
      name: "Priya Sharma",
      company: "TechNova Solutions",
      role: "Data Analyst",
      location: "Bengaluru",
      experience: "3 years",
      status: "Actively looking for job",
      matchPercent: 95,
      avatar,
      skills: ["Python", "Tableau", "SQL", "Responsive Design"],
    },
    {
      id: 5,
      name: "Amit Verma",
      company: "InnoTech Pvt Ltd",
      role: "Frontend Developer",
      location: "Hyderabad",
      experience: "2 years",
      status: "Actively looking for job",
      matchPercent: 88,
      avatar,
      skills: ["React", "JavaScript", "CSS", "Redux"],
    },
    {
      id: 6,
      name: "Amit Verma",
      company: "InnoTech Pvt Ltd",
      role: "Frontend Developer",
      location: "Hyderabad",
      experience: "2 years",
      status: "Actively looking for job",
      matchPercent: 88,
      avatar,
      skills: ["React", "JavaScript", "CSS", "Redux"],
    },
     {
      id: 7,
      name: "Priya Sharma",
      company: "TechNova Solutions",
      role: "Data Analyst",
      location: "Bengaluru",
      experience: "3 years",
      status: "Actively looking for job",
      matchPercent: 88,
      avatar,
      skills: ["Python", "Tableau", "SQL", "Responsive Design"],
    },
    {
      id: 8,
      name: "Amit Verma",
      company: "InnoTech Pvt Ltd",
      role: "Frontend Developer",
      location: "Hyderabad",
      experience: "2 years",
      status: "Actively looking for job",
      matchPercent: 88,
      avatar,
      skills: ["React", "JavaScript", "CSS", "Redux"],
    },
     {
      id: 9,
      name: "Priya Sharma",
      company: "TechNova Solutions",
      role: "Data Analyst",
      location: "Bengaluru",
      experience: "3 years",
      status: "Not Looking",
      matchPercent: 88,
      avatar,
      skills: ["Python", "Tableau", "SQL", "Responsive Design"],
    },
  ],
};

export default InterviewedData;
