import img1 from "../../../assets/Toptalent/image-view-one.jpg";
import img2 from "../../../assets/Toptalent/image-view-two.jpg";
import img3 from "../../../assets/Toptalent/image-view-three.jpg";
import img4 from "../../../assets/Toptalent/image-view-four.jpg";
import img5 from "../../../assets/Toptalent/image-view-five.jpg";

const talentProfiles = [
  {
    id: 1,
    name: "Prashanthi",
    company: "TechNova Solutions",
    role: "Senior Frontend Developer",
    location: "Bengaluru",
    experience: "3 years",
    activelyLooking: true,
    skills: ["React.js", "JavaScript (ES6+)", "Next.js", "Responsive Design"],
    image: img1,
  },
  {
    id: 2,
    name: "Aarav",
    company: "Innovix Labs",
    role: "Full Stack Developer",
    location: "Mumbai",
    experience: "4 years",
    activelyLooking: true,
    skills: ["Node.js", "Express", "MongoDB", "React.js"],
    image: img2,
  },
  {
    id: 3,
    name: "Sanya",
    company: "CodeCrafters Inc",
    role: "UI/UX Designer",
    location: "Delhi",
    experience: "5 years",
    activelyLooking: true,
    skills: ["Figma", "Sketch", "Adobe XD", "Responsive Design"],
    image: img3,
  },
  {
    id: 4,
    name: "Rohan",
    company: "Appify Solutions",
    role: "Mobile App Developer",
    location: "Pune",
    experience: "2 years",
    activelyLooking: true,
    skills: ["Flutter", "React Native", "Dart", "UI Design"],
    image: img4,
  },
  {
    id: 5,
    name: "Meera",
    company: "NextGen Tech",
    role: "Backend Developer",
    location: "Hyderabad",
    experience: "6 years",
    activelyLooking: true,
    skills: ["Python", "Django", "PostgreSQL", "REST APIs"],
    image: img5,
  },
  {
    id: 6,
    name: "Prashanthi",
    company: "TechNova Solutions",
    role: "Senior Frontend Developer",
    location: "Bengaluru",
    experience: "3 years",
    activelyLooking: true,
    skills: ["React.js", "JavaScript (ES6+)", "Next.js", "Responsive Design"],
    image: img1,
  },
  {
    id: 7,
    name: "Aarav",
    company: "Innovix Labs",
    role: "Full Stack Developer",
    location: "Mumbai",
    experience: "4 years",
    activelyLooking: true,
    skills: ["Node.js", "Express", "MongoDB", "React.js"],
    image: img2,
  },
  {
    id: 8,
    name: "Sanya",
    company: "CodeCrafters Inc",
    role: "UI/UX Designer",
    location: "Delhi",
    experience: "5 years",
    activelyLooking: true,
    skills: ["Figma", "Sketch", "Adobe XD", "Responsive Design"],
    image: img3,
  },
  {
    id: 9,
    name: "Rohan",
    company: "Appify Solutions",
    role: "Mobile App Developer",
    location: "Pune",
    experience: "2 years",
    activelyLooking: true,
    skills: ["Flutter", "React Native", "Dart", "UI Design"],
    image: img4,
  },
  {
    id: 10,
    name: "Meera",
    company: "NextGen Tech",
    role: "Backend Developer",
    location: "Hyderabad",
    experience: "6 years",
    activelyLooking: true,
    skills: ["Python", "Django", "PostgreSQL", "REST APIs"],
    image: img5,
  },
];

export default talentProfiles;
