import aishwaryaImg from "../../../../assets/MentorPage/assets/image-five.jpg";
import rajivImg from "../../../../assets/MentorPage/assets/image-six.jpg";
import abhinavImg from "../../../../assets/MentorPage/assets/image-seven.jpg";
import snehaImg from "../../../../assets/MentorPage/assets/image-eight.jpg";

const jobSeekersData = [
  {
    id: "js-aishwarya",
    name: "Aishwarya Sharma",
    role: "UI/UX Designer, Fresher",
    image: aishwaryaImg,
    skills: ["Figma", "Sketch", "Wireframing"],
    projects: 3,
    interests: "User Interfaces, App Design",
  },
  {
    id: "js-rajiv",
    name: "Rajiv Kapoor",
    role: "Full Stack Developer",
    image: rajivImg,
    skills: ["React", "Node", "Express"],
    projects: 6,
    interests: "Backend Systems, APIs",
  },
  {
    id: "js-abhinav",
    name: "Abhinav Nair",
    role: "Frontend Developer",
    image: abhinavImg,
    skills: ["HTML", "CSS", "Vue"],
    projects: 4,
    interests: "UI Development, Web Apps",
  },
  {
    id: "js-sneha",
    name: "Sneha Prasad",
    role: "Data Analyst Intern",
    image: snehaImg,
    skills: ["Python", "Pandas", "Excel"],
    projects: 5,
    interests: "Data Cleaning, Visualization",
  },
  // Duplicate with modified content
  {
    id: "js-aishwarya-2",
    name: "Aishwarya Sharma",
    role: "Product Designer",
    image: aishwaryaImg,
    skills: ["Adobe XD", "Prototyping", "Design Systems"],
    projects: 5,
    interests: "UX Research, Storyboarding",
  },
  {
    id: "js-rajiv-2",
    name: "Rajiv Kapoor",
    role: "Backend Engineer",
    image: rajivImg,
    skills: ["Java", "Spring Boot", "SQL"],
    projects: 7,
    interests: "Microservices, DevOps",
  },
  {
    id: "js-abhinav-2",
    name: "Abhinav Nair",
    role: "Mobile App Developer",
    image: abhinavImg,
    skills: ["React Native", "Flutter", "Dart"],
    projects: 3,
    interests: "Cross-platform Apps",
  },
  {
    id: "js-sneha-2",
    name: "Sneha Prasad",
    role: "AI Enthusiast",
    image: snehaImg,
    skills: ["TensorFlow", "NLP", "Deep Learning"],
    projects: 6,
    interests: "AI Research, Chatbots",
  },
  // Add more variations for at least 24 total
  {
    id: "js-aishwarya-3",
    name: "Aishwarya Sharma",
    role: "Interaction Designer",
    image: aishwaryaImg,
    skills: ["Usability Testing", "User Flows", "Personas"],
    projects: 4,
    interests: "User Behavior, Accessibility",
  },
  {
    id: "js-rajiv-3",
    name: "Rajiv Kapoor",
    role: "Cloud Engineer",
    image: rajivImg,
    skills: ["AWS", "Docker", "Kubernetes"],
    projects: 8,
    interests: "Cloud Deployment, CI/CD",
  },
  {
    id: "js-abhinav-3",
    name: "Abhinav Nair",
    role: "Technical Writer",
    image: abhinavImg,
    skills: ["Markdown", "Documentation", "Git"],
    projects: 2,
    interests: "Open Source, Developer Docs",
  },
  {
    id: "js-sneha-3",
    name: "Sneha Prasad",
    role: "Statistician",
    image: snehaImg,
    skills: ["R", "SPSS", "Data Modeling"],
    projects: 5,
    interests: "Surveys, Statistical Methods",
  },
  {
    id: "js-aishwarya-2",
    name: "Aishwarya Sharma",
    role: "Product Designer",
    image: aishwaryaImg,
    skills: ["Adobe XD", "Prototyping", "Design Systems"],
    projects: 5,
    interests: "UX Research, Storyboarding",
  },
  {
    id: "js-rajiv-2",
    name: "Rajiv Kapoor",
    role: "Backend Engineer",
    image: rajivImg,
    skills: ["Java", "Spring Boot", "SQL"],
    projects: 7,
    interests: "Microservices, DevOps",
  },
  {
    id: "js-abhinav-2",
    name: "Abhinav Nair",
    role: "Mobile App Developer",
    image: abhinavImg,
    skills: ["React Native", "Flutter", "Dart"],
    projects: 3,
    interests: "Cross-platform Apps",
  },
  {
    id: "js-sneha-2",
    name: "Sneha Prasad",
    role: "AI Enthusiast",
    image: snehaImg,
    skills: ["TensorFlow", "NLP", "Deep Learning"],
    projects: 6,
    interests: "AI Research, Chatbots",
  },
  // Add more variations for at least 24 total
  {
    id: "js-aishwarya-3",
    name: "Aishwarya Sharma",
    role: "Interaction Designer",
    image: aishwaryaImg,
    skills: ["Usability Testing", "User Flows", "Personas"],
    projects: 4,
    interests: "User Behavior, Accessibility",
  },
  {
    id: "js-rajiv-3",
    name: "Rajiv Kapoor",
    role: "Cloud Engineer",
    image: rajivImg,
    skills: ["AWS", "Docker", "Kubernetes"],
    projects: 8,
    interests: "Cloud Deployment, CI/CD",
  },
  {
    id: "js-abhinav-3",
    name: "Abhinav Nair",
    role: "Technical Writer",
    image: abhinavImg,
    skills: ["Markdown", "Documentation", "Git"],
    projects: 2,
    interests: "Open Source, Developer Docs",
  },
];

export default jobSeekersData;
